---
- name: Install packages
  apt:
    name: "{{ item.name }}"
    state: present
  loop: "{{ packages }}"
- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
- name: Update repository cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
    force_apt_get: yes
- name: Install Docker
  apt:
    name: "{{item}}"
    state: present
  loop:
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
    - docker-ce-rootless-extras
- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
- name: Start Docker service
  systemd:
    name: docker
    state: started
    enabled: yes
