---
- hosts: all
  become: true
  ignore_errors: yes
  tasks:
    - name: Update DNS server
      lineinfile:
        path: /etc/resolv.conf
        regexp: '^nameserver'
        line: 'nameserver 178.22.122.100'
  roles:
    - install-tools
